### PR TITLE
Ported module for 1.7

### PR DESCRIPTION
**Pull request by aleeks**
Ported module for 1.7

ping @aleeks @maximebiloe

### CODE REVIEW

**Comment by maximebiloe** [comment]
👻

**Comment by aleeks** [comment]
Hello @kpodemski 
Thank you for having turned the problem!!
Do you know where the problem is, I didn't see where and for lower than 5.4... I just make refacto..

**Comment by kpodemski** [comment]
Shorthand array

**Comment by maximebiloe** [comment]
We just released a new version of the module.
Thanks for reporting @kpodemski!

**Pull request merged**
