### PR TITLE
Remove deprecated functions

### LINKED ISSUE #28069: statsdata module is incompatible with latest jQuery and throws errors
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Statsdata module is using .live method, which is incompatible with latest jQuery 3 and throws errors into browser console.

See: https://github.com/PrestaShop/statsdata/blob/dev/statsdata.php#L129

### Expected behavior

Module should not be using this method.

### Steps to reproduce

1. Rebuild core.js without a jQuery migrate.
2. Install statsdatamodule.
3. Go to FO and check console on any page.

---
1. Go to `themes` folder
2. Delete jquery-migrate from `package.json` and from `_core/js/theme.js`
4. Run `npm install` and `npm run build`
5. Install `statsdatamodule`
6. Enable options and save 
image
7. Go to FO and check console on any page

### PrestaShop version(s) where the bug happened

develop

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

statsdata

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Remove deprecated functions so the module works without jQuery migrate.
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#28069
| How to test?  | Check that data still come in.

Ping @NeOMakinG

### CODE REVIEW

**Review by Progi1984 — DISMISSED** [review]

**Review by kpodemski — DISMISSED** [review]

**Review by NeOMakinG — DISMISSED** [review]

**Comment by kpodemski** [comment]
Hey @Hlavtox 

There's a conflict because othe contibutor introduced the code changing `unload` to something more reliable in other PR. Could you check if your changes are still relevant?

ps: contact me on Slack, please :D

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by szavadskiy — APPROVED** [review]
Hello, @Hlavtox 
Its LGTM, after installing your PR I didn't find an error in the console.
Thank you for your PR. :rocket:

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR, LGTM and QA :heavy_check_mark: 
And thanks @szavadskiy for testing the PR :clap: 

Thanks!

**Comment by Progi1984** [comment]
Thanks @Hlavtox & @hibatallahAouadni

**Comment by Robin-Fischer-PS** [comment]
And thanks a lot @szavadskiy ! Congrats for your first PR tested :tada:

**Comment by Progi1984** [comment]
Sorry @szavadskiy : Big Thanks.

**Pull request merged**
